# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-03 19:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0022_agency_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms_qty', models.IntegerField(default=0)),
                ('guests_qty', models.IntegerField(default=0)),
                ('transport', models.CharField(max_length=50)),
                ('departure_date', models.DateField()),
                ('customer_address', models.CharField(max_length=200)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Agency')),
                ('madinah_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.MadinahHotel')),
                ('makkah_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.MakkahHotel')),
                ('room_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.RoomClass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
