# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-07 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20180305_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='customer_address',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='departure_date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='guests_qty',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='madinah_hotel',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='makkah_hotel',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='room_size',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='rooms_qty',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='transport',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.AddField(
            model_name='reservation',
            name='departures_qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservation',
            name='package',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='username',
            field=models.CharField(default='jhjhg', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
