# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-13 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20180313_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='departure_date',
            field=models.DateField(),
        ),
    ]
