# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-13 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_reservation_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
