# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-13 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20180313_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='pre_phone_number',
        ),
    ]
