# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-15 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_remove_reservation_pre_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='departure_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
