# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-19 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_auto_20180315_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
