# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-20 20:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('facebook_page', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('stars', models.IntegerField(default=0)),
                ('city', models.CharField(max_length=7)),
                ('departure', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MadinahHotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_from_center', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MakkahHotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_from_center', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('level', models.IntegerField(default=3)),
                ('makkah_nights', models.IntegerField(default=0)),
                ('madinah_nights', models.IntegerField(default=0)),
                ('airlines', models.CharField(blank=True, max_length=50)),
                ('ticket_cost', models.IntegerField(default=0)),
                ('madinah_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.MadinahHotel')),
                ('makkah_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.MakkahHotel')),
            ],
        ),
        migrations.CreateModel(
            name='Photoshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='photoshots')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=500)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Agency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('currency', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RoomClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('class_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='room_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.RoomClass'),
        ),
        migrations.AddField(
            model_name='package',
            name='rooms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Room'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='photoshots',
            field=models.ManyToManyField(to='catalogue.Photoshot'),
        ),
        migrations.AddField(
            model_name='agency',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Country'),
        ),
        migrations.AddField(
            model_name='agency',
            name='packages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Package'),
        ),
        migrations.AddField(
            model_name='agency',
            name='photos',
            field=models.ManyToManyField(to='catalogue.Photoshot'),
        ),
    ]
