# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-21 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='thumbnail',
            field=models.FileField(null=True, upload_to='thumbnails/'),
        ),
    ]
