# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-21 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_package_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='photos',
        ),
    ]
