# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-21 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_remove_agency_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='packages',
        ),
        migrations.AddField(
            model_name='package',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Agency'),
        ),
    ]
