# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-21 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20180221_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='departure',
        ),
    ]
