# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-21 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_remove_hotel_departure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='madinahhotel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='makkahhotel',
            name='id',
        ),
        migrations.AddField(
            model_name='madinahhotel',
            name='hotel_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogue.Hotel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='makkahhotel',
            name='hotel_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogue.Hotel'),
            preserve_default=False,
        ),
    ]
