# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-21 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_remove_hotel_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='price',
        ),
        migrations.AddField(
            model_name='package',
            name='person_price',
            field=models.IntegerField(default=0),
        ),
    ]
