# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-21 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_auto_20180221_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='nights',
            field=models.IntegerField(default=0),
        ),
    ]
