# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-21 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_package_nights'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='thumbnail',
            field=models.FileField(null=True, upload_to='thumbnails/'),
        ),
    ]
