# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-21 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_hotel_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='rooms',
        ),
        migrations.AddField(
            model_name='package',
            name='rooms',
            field=models.ManyToManyField(to='catalogue.Room'),
        ),
    ]
