# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-21 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_auto_20180221_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='rooms',
        ),
        migrations.AddField(
            model_name='room',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Package'),
        ),
    ]
