# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-21 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_auto_20180221_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='person_price',
            new_name='prices_start_from',
        ),
        migrations.AddField(
            model_name='room',
            name='person_price',
            field=models.IntegerField(default=0),
        ),
    ]
