# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-24 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_auto_20180221_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='logo',
            field=models.FileField(null=True, upload_to='logos/'),
        ),
    ]
