# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-24 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_agency_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_code',
            field=models.CharField(default='JO', max_length=3),
        ),
    ]
