# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-25 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_country_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='double_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='five_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='include_transportation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='quad_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='triple_cost',
            field=models.IntegerField(default=0),
        ),
    ]
