# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-25 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0018_package_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='madinah_hotel_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='package',
            name='makkah_hotel_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='package',
            name='transport',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='package',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
