# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-25 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_auto_20180225_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='madinah_hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.MadinahHotel'),
        ),
        migrations.AlterField(
            model_name='package',
            name='makkah_hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.MakkahHotel'),
        ),
    ]
