# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-03 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0021_auto_20180225_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
