# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-03 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0022_agency_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='package',
            name='madinah_hotel',
        ),
        migrations.RemoveField(
            model_name='package',
            name='makkah_hotel',
        ),
        migrations.RemoveField(
            model_name='package',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='room',
            name='package',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_class',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
