# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-03 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0023_auto_20180303_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='rooms',
            field=models.ManyToManyField(to='catalogue.RoomClass'),
        ),
        migrations.AlterField(
            model_name='roomclass',
            name='class_code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='available_dates',
            field=models.ManyToManyField(to='catalogue.Date'),
        ),
    ]
