# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-04 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0024_auto_20180303_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='bus_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agency',
            name='flight_cost',
            field=models.IntegerField(default=0),
        ),
    ]
