# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-04 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0025_auto_20180304_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='bus_cost',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='flight_cost',
        ),
    ]
