# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-04 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0026_auto_20180304_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_room_cost', models.IntegerField(default=0)),
                ('double_room_cost', models.IntegerField(default=0)),
                ('trip_room_cost', models.IntegerField(default=0)),
                ('quad_room_cost', models.IntegerField(default=0)),
                ('quin_room_cost', models.IntegerField(default=0)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Agency')),
                ('madinah_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.MadinahHotel')),
                ('makkah_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.MakkahHotel')),
            ],
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='rooms',
        ),
    ]
