# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-05 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_auto_20180304_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='transport',
            field=models.CharField(default='BUS', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='package',
            unique_together=set([('agency', 'madinah_hotel', 'makkah_hotel', 'transport')]),
        ),
    ]
