# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-05 19:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0028_auto_20180305_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='madinah_hotel_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='makkah_hotel_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
