# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-06 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0029_auto_20180305_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='agency',
            new_name='catalogue_agency',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='user',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='agency',
            name='dashboard_agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Agency'),
        ),
        migrations.AddField(
            model_name='package',
            name='is_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='updated_double_room_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='updated_quad_room_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='updated_quin_room_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='updated_single_room_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='updated_trip_room_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='package',
            unique_together=set([]),
        ),
    ]
