# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-06 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0030_auto_20180306_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='catalogue_agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Agency'),
        ),
        migrations.AlterField(
            model_name='package',
            name='madinah_hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.MadinahHotel'),
        ),
        migrations.AlterField(
            model_name='package',
            name='makkah_hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.MakkahHotel'),
        ),
    ]
