# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-06 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0032_auto_20180306_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='supplier_agency',
            new_name='supplier_account_agency',
        ),
    ]
