# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-07 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0033_auto_20180306_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
