# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-07 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0034_auto_20180307_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='prices_start_from',
            field=models.IntegerField(default=0),
        ),
    ]
