# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-07 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0035_package_prices_start_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='prices_start_from',
        ),
        migrations.AddField(
            model_name='agency',
            name='prices_start_from',
            field=models.IntegerField(default=0),
        ),
    ]
