# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-07 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0037_package_prices_start_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
