# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-08 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0038_auto_20180307_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='distinct',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='madinah_hotel_stars',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='makkah_hotel_stars',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
