# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-08 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0039_auto_20180308_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='airlines',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
