# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-08 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0040_package_airlines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='airlines',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
