# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-11 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0041_auto_20180308_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='available_dates',
        ),
        migrations.AddField(
            model_name='date',
            name='day',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='available_dates',
            field=models.ManyToManyField(blank=True, to='catalogue.Date'),
        ),
    ]
