# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-15 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0042_auto_20180311_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='month',
            new_name='madinah_hotel_distance',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='year',
            new_name='makkah_hotel_distance',
        ),
        migrations.AddField(
            model_name='package',
            name='bus_capacity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='package',
            name='bus_model',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
