# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-18 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0043_auto_20180315_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='country',
        ),
        migrations.AlterField(
            model_name='agency',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Country'),
        ),
    ]
