# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-18 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0044_auto_20180318_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='bus_capacity',
            field=models.IntegerField(null=True),
        ),
    ]
