# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-19 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0045_auto_20180318_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='supplier_account_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Agency'),
        ),
    ]
