# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-19 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0046_auto_20180319_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='bus_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
