# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-19 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0047_auto_20180319_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='madinah_nights',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='makkah_nights',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='nights',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
