# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-19 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0048_auto_20180319_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='meal',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
