# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-19 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0049_package_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
